version: '3'
services:
  tracking:
    build: .
    container_name: "traccar"
    ports:
        - "8082:8082"
        - "5000-5150:5000-5150"
    depends_on: 
        - database  
  database:
    image: "postgres" 
    container_name: "db"
    env_file:
      - .database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ 
    ports: 
        - "5432:5432" 
volumes:
  database-data: 

